name: Daily Weather Data Collection

on:
  schedule:
    - cron: '0 10 * * *' # Runs daily at 10 AM
  workflow_dispatch:

permissions:
  contents: write
    
jobs:
  collect-weather-data:
    runs-on: ubuntu-latest

    steps:
      # Checkout the current repository
      - name: Checkout current repository
        uses: actions/checkout@v2

      # Clone the computer-infrastructure repository
      - name: Clone computer-infrastructure repository
        uses: actions/checkout@v2
        with:
          repository: https://github.com/aoifeflav/computer-infrastructure.git
          path: computer-infrastructure # Optional custom directory for the cloned repo

      # Make weather.sh executable
      - name: Make weather.sh executable
        run: chmod +x ./weather.sh

      # Run the weather.sh script
      - name: Run weather.sh script
        run: ./weather.sh

      # Commit and push changes back to the repository
      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update weather data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}