name: Daily Weather Data Collection

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch: 

jobs:
  collect-weather-data:
    runs-on: ubuntu-latest
    steps:
      - name: Run weather.sh script
        run: ./weather.sh
